/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.102.0
  Forc version: 0.69.1
  Fuel-Core version: 0.47.1
*/

import { Contract as __Contract, Interface } from 'fuels';
import type {
  Provider,
  Account,
  StorageSlot,
  Address,
  BigNumberish,
  BN,
  FunctionFragment,
  InvokeFunction,
} from 'fuels';

import type { Option } from './common';

const abi = {
  programType: 'contract',
  specVersion: '1.1',
  encodingVersion: '1',
  concreteTypes: [
    {
      type: '()',
      concreteTypeId: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
    },
    {
      type: 'bool',
      concreteTypeId: 'b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903',
    },
    {
      type: 'enum std::option::Option<u8>',
      concreteTypeId: '2da102c46c7263beeed95818cd7bee801716ba8303dddafdcd0f6c9efda4a0f1',
      metadataTypeId: 0,
      typeArguments: ['c89951a24c6ca28c13fd1cfdc646b2b656d69e61a92b91023be7eb58eb914b6b'],
    },
    {
      type: 'u64',
      concreteTypeId: '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
    },
    {
      type: 'u8',
      concreteTypeId: 'c89951a24c6ca28c13fd1cfdc646b2b656d69e61a92b91023be7eb58eb914b6b',
    },
  ],
  metadataTypes: [
    {
      type: 'enum std::option::Option',
      metadataTypeId: 0,
      components: [
        {
          name: 'None',
          typeId: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
        },
        {
          name: 'Some',
          typeId: 1,
        },
      ],
      typeParameters: [1],
    },
    {
      type: 'generic T',
      metadataTypeId: 1,
    },
  ],
  functions: [
    {
      name: 'is_empty',
      inputs: [],
      output: 'b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903',
      attributes: [
        {
          name: 'storage',
          arguments: ['read'],
        },
      ],
    },
    {
      name: 'len',
      inputs: [],
      output: '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
      attributes: [
        {
          name: 'storage',
          arguments: ['read'],
        },
      ],
    },
    {
      name: 'peek',
      inputs: [],
      output: '2da102c46c7263beeed95818cd7bee801716ba8303dddafdcd0f6c9efda4a0f1',
      attributes: [
        {
          name: 'storage',
          arguments: ['read'],
        },
      ],
    },
    {
      name: 'pop',
      inputs: [],
      output: '2da102c46c7263beeed95818cd7bee801716ba8303dddafdcd0f6c9efda4a0f1',
      attributes: [
        {
          name: 'storage',
          arguments: ['read', 'write'],
        },
      ],
    },
    {
      name: 'push',
      inputs: [
        {
          name: 'value',
          concreteTypeId: 'c89951a24c6ca28c13fd1cfdc646b2b656d69e61a92b91023be7eb58eb914b6b',
        },
      ],
      output: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
      attributes: [
        {
          name: 'storage',
          arguments: ['read', 'write'],
        },
      ],
    },
    {
      name: 'remove',
      inputs: [
        {
          name: 'val',
          concreteTypeId: 'c89951a24c6ca28c13fd1cfdc646b2b656d69e61a92b91023be7eb58eb914b6b',
        },
      ],
      output: 'b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903',
      attributes: [
        {
          name: 'storage',
          arguments: ['read', 'write'],
        },
      ],
    },
  ],
  loggedTypes: [],
  messagesTypes: [],
  configurables: [],
  errorCodes: {},
};

const storageSlots: StorageSlot[] = [];

export class MaxHeapTestInterface extends Interface {
  constructor() {
    super(abi);
  }

  declare functions: {
    is_empty: FunctionFragment;
    len: FunctionFragment;
    peek: FunctionFragment;
    pop: FunctionFragment;
    push: FunctionFragment;
    remove: FunctionFragment;
  };
}

export class MaxHeapTest extends __Contract {
  static readonly abi = abi;
  static readonly storageSlots = storageSlots;

  declare interface: MaxHeapTestInterface;
  declare functions: {
    is_empty: InvokeFunction<[], boolean>;
    len: InvokeFunction<[], BN>;
    peek: InvokeFunction<[], Option<number>>;
    pop: InvokeFunction<[], Option<number>>;
    push: InvokeFunction<[value: BigNumberish], void>;
    remove: InvokeFunction<[val: BigNumberish], boolean>;
  };

  constructor(id: string | Address, accountOrProvider: Account | Provider) {
    super(id, abi, accountOrProvider);
  }
}
