"use strict";
/* Autogenerated file. Do not edit manually. */
Object.defineProperty(exports, "__esModule", { value: true });
exports.OrderBookProxy = exports.OrderBookProxyInterface = exports.SetProxyOwnerErrorOutput = exports.SetProxyOwnerErrorInput = exports.InitializationErrorOutput = exports.InitializationErrorInput = exports.AccessErrorOutput = exports.AccessErrorInput = void 0;
/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */
/*
  Fuels version: 0.102.0
  Forc version: 0.69.1
  Fuel-Core version: 0.47.1
*/
const fuels_1 = require("fuels");
var AccessErrorInput;
(function (AccessErrorInput) {
    AccessErrorInput["NotOwner"] = "NotOwner";
})(AccessErrorInput || (exports.AccessErrorInput = AccessErrorInput = {}));
var AccessErrorOutput;
(function (AccessErrorOutput) {
    AccessErrorOutput["NotOwner"] = "NotOwner";
})(AccessErrorOutput || (exports.AccessErrorOutput = AccessErrorOutput = {}));
var InitializationErrorInput;
(function (InitializationErrorInput) {
    InitializationErrorInput["CannotReinitialized"] = "CannotReinitialized";
})(InitializationErrorInput || (exports.InitializationErrorInput = InitializationErrorInput = {}));
var InitializationErrorOutput;
(function (InitializationErrorOutput) {
    InitializationErrorOutput["CannotReinitialized"] = "CannotReinitialized";
})(InitializationErrorOutput || (exports.InitializationErrorOutput = InitializationErrorOutput = {}));
var SetProxyOwnerErrorInput;
(function (SetProxyOwnerErrorInput) {
    SetProxyOwnerErrorInput["CannotUninitialize"] = "CannotUninitialize";
})(SetProxyOwnerErrorInput || (exports.SetProxyOwnerErrorInput = SetProxyOwnerErrorInput = {}));
var SetProxyOwnerErrorOutput;
(function (SetProxyOwnerErrorOutput) {
    SetProxyOwnerErrorOutput["CannotUninitialize"] = "CannotUninitialize";
})(SetProxyOwnerErrorOutput || (exports.SetProxyOwnerErrorOutput = SetProxyOwnerErrorOutput = {}));
const abi = {
    programType: 'contract',
    specVersion: '1.1',
    encodingVersion: '1',
    concreteTypes: [
        {
            type: '()',
            concreteTypeId: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
        },
        {
            type: 'enum ownership::errors::InitializationError',
            concreteTypeId: 'b1fddf488ccb9e63d11888b2750bbd1280a1ae1c49f2d6637fd4cf1e930d1468',
            metadataTypeId: 1,
        },
        {
            type: 'enum src5::AccessError',
            concreteTypeId: 'f1247475d0d1466599267010f088190f8664dd31663a40c5d5e525d8e64b995d',
            metadataTypeId: 2,
        },
        {
            type: 'enum src5::State',
            concreteTypeId: '287a382c1e0b1f11d12a422e77a248d27761327cd17515cc6e6369d528cf31ca',
            metadataTypeId: 3,
        },
        {
            type: 'enum std::identity::Identity',
            concreteTypeId: 'ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335',
            metadataTypeId: 4,
        },
        {
            type: 'enum std::option::Option<struct std::contract_id::ContractId>',
            concreteTypeId: '0d79387ad3bacdc3b7aad9da3a96f4ce60d9a1b6002df254069ad95a3931d5c8',
            metadataTypeId: 5,
            typeArguments: ['29c10735d33b5159f0c71ee1dbd17b36a3e69e41f00fab0d42e1bd9f428d8a54'],
        },
        {
            type: 'enum upgradability::errors::SetProxyOwnerError',
            concreteTypeId: '077440f455d1eb83361f2183e189067ac3bf4bb6166b7a0630f371593ebb274e',
            metadataTypeId: 6,
        },
        {
            type: 'str',
            concreteTypeId: '8c25cb3686462e9a86d2883c5688a22fe738b0bbc85f458d2d2b5f3f667c6d5a',
        },
        {
            type: 'struct contract_schema::proxys::OwnershipTransferredEvent',
            concreteTypeId: '1a4a391e4e527b56f6e488bce418bfd7ff45c5ee2956b4891af265057da0ae69',
            metadataTypeId: 8,
        },
        {
            type: 'struct std::contract_id::ContractId',
            concreteTypeId: '29c10735d33b5159f0c71ee1dbd17b36a3e69e41f00fab0d42e1bd9f428d8a54',
            metadataTypeId: 10,
        },
        {
            type: 'struct upgradability::events::ProxyOwnerSet',
            concreteTypeId: '3c23b359912e25002dc894bca0ea08e15bcae108cb5ed17b9cb5ca3fed321e5d',
            metadataTypeId: 12,
        },
        {
            type: 'struct upgradability::events::ProxyTargetSet',
            concreteTypeId: '47d9868a6266fb294f68de9d33690c9e627c37425d784cc82b7a7b7e5635b779',
            metadataTypeId: 13,
        },
    ],
    metadataTypes: [
        {
            type: 'b256',
            metadataTypeId: 0,
        },
        {
            type: 'enum ownership::errors::InitializationError',
            metadataTypeId: 1,
            components: [
                {
                    name: 'CannotReinitialized',
                    typeId: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
                },
            ],
        },
        {
            type: 'enum src5::AccessError',
            metadataTypeId: 2,
            components: [
                {
                    name: 'NotOwner',
                    typeId: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
                },
            ],
        },
        {
            type: 'enum src5::State',
            metadataTypeId: 3,
            components: [
                {
                    name: 'Uninitialized',
                    typeId: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
                },
                {
                    name: 'Initialized',
                    typeId: 4,
                },
                {
                    name: 'Revoked',
                    typeId: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
                },
            ],
        },
        {
            type: 'enum std::identity::Identity',
            metadataTypeId: 4,
            components: [
                {
                    name: 'Address',
                    typeId: 9,
                },
                {
                    name: 'ContractId',
                    typeId: 10,
                },
            ],
        },
        {
            type: 'enum std::option::Option',
            metadataTypeId: 5,
            components: [
                {
                    name: 'None',
                    typeId: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
                },
                {
                    name: 'Some',
                    typeId: 7,
                },
            ],
            typeParameters: [7],
        },
        {
            type: 'enum upgradability::errors::SetProxyOwnerError',
            metadataTypeId: 6,
            components: [
                {
                    name: 'CannotUninitialize',
                    typeId: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
                },
            ],
        },
        {
            type: 'generic T',
            metadataTypeId: 7,
        },
        {
            type: 'struct contract_schema::proxys::OwnershipTransferredEvent',
            metadataTypeId: 8,
            components: [
                {
                    name: 'previous_owner',
                    typeId: 5,
                    typeArguments: [
                        {
                            name: '',
                            typeId: 4,
                        },
                    ],
                },
                {
                    name: 'new_owner',
                    typeId: 4,
                },
                {
                    name: 'timestamp',
                    typeId: 11,
                },
            ],
        },
        {
            type: 'struct std::address::Address',
            metadataTypeId: 9,
            components: [
                {
                    name: 'bits',
                    typeId: 0,
                },
            ],
        },
        {
            type: 'struct std::contract_id::ContractId',
            metadataTypeId: 10,
            components: [
                {
                    name: 'bits',
                    typeId: 0,
                },
            ],
        },
        {
            type: 'struct std::time::Time',
            metadataTypeId: 11,
            components: [
                {
                    name: 'unix',
                    typeId: 14,
                },
            ],
        },
        {
            type: 'struct upgradability::events::ProxyOwnerSet',
            metadataTypeId: 12,
            components: [
                {
                    name: 'new_proxy_owner',
                    typeId: 3,
                },
            ],
        },
        {
            type: 'struct upgradability::events::ProxyTargetSet',
            metadataTypeId: 13,
            components: [
                {
                    name: 'new_target',
                    typeId: 10,
                },
            ],
        },
        {
            type: 'u64',
            metadataTypeId: 14,
        },
    ],
    functions: [
        {
            name: 'proxy_target',
            inputs: [],
            output: '0d79387ad3bacdc3b7aad9da3a96f4ce60d9a1b6002df254069ad95a3931d5c8',
            attributes: [
                {
                    name: 'doc-comment',
                    arguments: [' Returns the target contract of the proxy contract.'],
                },
                {
                    name: 'doc-comment',
                    arguments: [''],
                },
                {
                    name: 'doc-comment',
                    arguments: [' # Returns'],
                },
                {
                    name: 'doc-comment',
                    arguments: [''],
                },
                {
                    name: 'doc-comment',
                    arguments: [
                        ' * [Option<ContractId>] - The new proxy contract to which all fallback calls will be passed or `None`.',
                    ],
                },
                {
                    name: 'doc-comment',
                    arguments: [''],
                },
                {
                    name: 'doc-comment',
                    arguments: [' # Number of Storage Accesses'],
                },
                {
                    name: 'doc-comment',
                    arguments: [''],
                },
                {
                    name: 'doc-comment',
                    arguments: [' * Reads: `1`'],
                },
                {
                    name: 'storage',
                    arguments: ['read'],
                },
            ],
        },
        {
            name: 'set_proxy_target',
            inputs: [
                {
                    name: 'new_target',
                    concreteTypeId: '29c10735d33b5159f0c71ee1dbd17b36a3e69e41f00fab0d42e1bd9f428d8a54',
                },
            ],
            output: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
            attributes: [
                {
                    name: 'doc-comment',
                    arguments: [' Change the target contract of the proxy contract.'],
                },
                {
                    name: 'doc-comment',
                    arguments: [''],
                },
                {
                    name: 'doc-comment',
                    arguments: [' # Additional Information'],
                },
                {
                    name: 'doc-comment',
                    arguments: [''],
                },
                {
                    name: 'doc-comment',
                    arguments: [' This method can only be called by the `proxy_owner`.'],
                },
                {
                    name: 'doc-comment',
                    arguments: [''],
                },
                {
                    name: 'doc-comment',
                    arguments: [' # Arguments'],
                },
                {
                    name: 'doc-comment',
                    arguments: [''],
                },
                {
                    name: 'doc-comment',
                    arguments: [
                        ' * `new_target`: [ContractId] - The new proxy contract to which all fallback calls will be passed.',
                    ],
                },
                {
                    name: 'doc-comment',
                    arguments: [''],
                },
                {
                    name: 'doc-comment',
                    arguments: [' # Reverts'],
                },
                {
                    name: 'doc-comment',
                    arguments: [''],
                },
                {
                    name: 'doc-comment',
                    arguments: [' * When not called by `proxy_owner`.'],
                },
                {
                    name: 'doc-comment',
                    arguments: [''],
                },
                {
                    name: 'doc-comment',
                    arguments: [' # Number of Storage Accesses'],
                },
                {
                    name: 'doc-comment',
                    arguments: [''],
                },
                {
                    name: 'doc-comment',
                    arguments: [' * Reads: `1`'],
                },
                {
                    name: 'doc-comment',
                    arguments: [' * Write: `1`'],
                },
                {
                    name: 'storage',
                    arguments: ['read', 'write'],
                },
            ],
        },
        {
            name: 'proxy_owner',
            inputs: [],
            output: '287a382c1e0b1f11d12a422e77a248d27761327cd17515cc6e6369d528cf31ca',
            attributes: [
                {
                    name: 'doc-comment',
                    arguments: [' Returns the owner of the proxy contract.'],
                },
                {
                    name: 'doc-comment',
                    arguments: [''],
                },
                {
                    name: 'doc-comment',
                    arguments: [' # Returns'],
                },
                {
                    name: 'doc-comment',
                    arguments: [''],
                },
                {
                    name: 'doc-comment',
                    arguments: [' * [State] - Represents the state of ownership for this contract.'],
                },
                {
                    name: 'doc-comment',
                    arguments: [''],
                },
                {
                    name: 'doc-comment',
                    arguments: [' # Number of Storage Accesses'],
                },
                {
                    name: 'doc-comment',
                    arguments: [''],
                },
                {
                    name: 'doc-comment',
                    arguments: [' * Reads: `1`'],
                },
                {
                    name: 'storage',
                    arguments: ['read'],
                },
            ],
        },
        {
            name: 'initialize_proxy',
            inputs: [],
            output: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
            attributes: [
                {
                    name: 'doc-comment',
                    arguments: [' Initializes the proxy contract.'],
                },
                {
                    name: 'doc-comment',
                    arguments: [''],
                },
                {
                    name: 'doc-comment',
                    arguments: [' # Additional Information'],
                },
                {
                    name: 'doc-comment',
                    arguments: [''],
                },
                {
                    name: 'doc-comment',
                    arguments: [
                        ' This method sets the storage values using the values of the configurable constants `INITIAL_TARGET` and `INITIAL_OWNER`.',
                    ],
                },
                {
                    name: 'doc-comment',
                    arguments: [' This then allows methods that write to storage to be called.'],
                },
                {
                    name: 'doc-comment',
                    arguments: [' This method can only be called once.'],
                },
                {
                    name: 'doc-comment',
                    arguments: [''],
                },
                {
                    name: 'doc-comment',
                    arguments: [' # Reverts'],
                },
                {
                    name: 'doc-comment',
                    arguments: [''],
                },
                {
                    name: 'doc-comment',
                    arguments: [' * When `storage::SRC14.proxy_owner` is not [State::Uninitialized].'],
                },
                {
                    name: 'doc-comment',
                    arguments: [''],
                },
                {
                    name: 'doc-comment',
                    arguments: [' # Number of Storage Accesses'],
                },
                {
                    name: 'doc-comment',
                    arguments: [''],
                },
                {
                    name: 'doc-comment',
                    arguments: [' * Writes: `2`'],
                },
                {
                    name: 'storage',
                    arguments: ['write'],
                },
            ],
        },
        {
            name: 'set_owner',
            inputs: [
                {
                    name: 'new_owner',
                    concreteTypeId: 'ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335',
                },
            ],
            output: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
            attributes: [
                {
                    name: 'doc-comment',
                    arguments: [' Changes proxy ownership to the passed State.'],
                },
                {
                    name: 'doc-comment',
                    arguments: [''],
                },
                {
                    name: 'doc-comment',
                    arguments: [' # Additional Information'],
                },
                {
                    name: 'doc-comment',
                    arguments: [''],
                },
                {
                    name: 'doc-comment',
                    arguments: [' This method can be used to transfer ownership between Identities or to revoke ownership.'],
                },
                {
                    name: 'doc-comment',
                    arguments: [''],
                },
                {
                    name: 'doc-comment',
                    arguments: [' # Arguments'],
                },
                {
                    name: 'doc-comment',
                    arguments: [''],
                },
                {
                    name: 'doc-comment',
                    arguments: [' * `new_proxy_owner`: [State] - The new state of the proxy ownership.'],
                },
                {
                    name: 'doc-comment',
                    arguments: [''],
                },
                {
                    name: 'doc-comment',
                    arguments: [' # Reverts'],
                },
                {
                    name: 'doc-comment',
                    arguments: [''],
                },
                {
                    name: 'doc-comment',
                    arguments: [' * When the sender is not the current proxy owner.'],
                },
                {
                    name: 'doc-comment',
                    arguments: [' * When the new state of the proxy ownership is [State::Uninitialized].'],
                },
                {
                    name: 'doc-comment',
                    arguments: [''],
                },
                {
                    name: 'doc-comment',
                    arguments: [' # Number of Storage Accesses'],
                },
                {
                    name: 'doc-comment',
                    arguments: [''],
                },
                {
                    name: 'doc-comment',
                    arguments: [' * Reads: `1`'],
                },
                {
                    name: 'doc-comment',
                    arguments: [' * Writes: `1`'],
                },
                {
                    name: 'storage',
                    arguments: ['read', 'write'],
                },
            ],
        },
    ],
    loggedTypes: [
        {
            logId: '17376141311665587813',
            concreteTypeId: 'f1247475d0d1466599267010f088190f8664dd31663a40c5d5e525d8e64b995d',
        },
        {
            logId: '10098701174489624218',
            concreteTypeId: '8c25cb3686462e9a86d2883c5688a22fe738b0bbc85f458d2d2b5f3f667c6d5a',
        },
        {
            logId: '5177317175553620777',
            concreteTypeId: '47d9868a6266fb294f68de9d33690c9e627c37425d784cc82b7a7b7e5635b779',
        },
        {
            logId: '12825652816513834595',
            concreteTypeId: 'b1fddf488ccb9e63d11888b2750bbd1280a1ae1c49f2d6637fd4cf1e930d1468',
        },
        {
            logId: '1894389395588545366',
            concreteTypeId: '1a4a391e4e527b56f6e488bce418bfd7ff45c5ee2956b4891af265057da0ae69',
        },
        {
            logId: '537125673719950211',
            concreteTypeId: '077440f455d1eb83361f2183e189067ac3bf4bb6166b7a0630f371593ebb274e',
        },
        {
            logId: '4333504463729730816',
            concreteTypeId: '3c23b359912e25002dc894bca0ea08e15bcae108cb5ed17b9cb5ca3fed321e5d',
        },
    ],
    messagesTypes: [],
    configurables: [
        {
            name: 'INITIAL_OWNER',
            concreteTypeId: '287a382c1e0b1f11d12a422e77a248d27761327cd17515cc6e6369d528cf31ca',
            offset: 11224,
            indirect: false,
        },
        {
            name: 'INITIAL_TARGET',
            concreteTypeId: '29c10735d33b5159f0c71ee1dbd17b36a3e69e41f00fab0d42e1bd9f428d8a54',
            offset: 11272,
            indirect: false,
        },
    ],
    errorCodes: {},
};
const storageSlots = [
    {
        key: '7bb458adc1d118713319a5baa00a2d049dd64d2916477d2688d76970c898cd55',
        value: '0000000000000000000000000000000000000000000000000000000000000000',
    },
    {
        key: '7bb458adc1d118713319a5baa00a2d049dd64d2916477d2688d76970c898cd56',
        value: '0000000000000000000000000000000000000000000000000000000000000000',
    },
    {
        key: 'bb79927b15d9259ea316f2ecb2297d6cc8851888a98278c0a2e03e1a091ea754',
        value: '0000000000000000000000000000000000000000000000000000000000000000',
    },
    {
        key: 'bb79927b15d9259ea316f2ecb2297d6cc8851888a98278c0a2e03e1a091ea755',
        value: '0000000000000000000000000000000000000000000000000000000000000000',
    },
];
class OrderBookProxyInterface extends fuels_1.Interface {
    constructor() {
        super(abi);
    }
}
exports.OrderBookProxyInterface = OrderBookProxyInterface;
class OrderBookProxy extends fuels_1.Contract {
    static abi = abi;
    static storageSlots = storageSlots;
    constructor(id, accountOrProvider) {
        super(id, abi, accountOrProvider);
    }
}
exports.OrderBookProxy = OrderBookProxy;
//# sourceMappingURL=OrderBookProxy.js.map