/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.102.0
  Forc version: 0.69.1
  Fuel-Core version: 0.47.1
*/

import { Contract as __Contract, Interface } from 'fuels';
import type {
  Provider,
  Account,
  StorageSlot,
  Address,
  BigNumberish,
  BN,
  Bytes,
  FunctionFragment,
  InvokeFunction,
  StdString,
  StrSlice,
} from 'fuels';

import type { Option, Enum, Vec } from './common';

export enum AccessErrorInput {
  NotOwner = 'NotOwner',
}
export enum AccessErrorOutput {
  NotOwner = 'NotOwner',
}
export type IdentityInput = Enum<{ Address: AddressInput; ContractId: ContractIdInput }>;
export type IdentityOutput = Enum<{ Address: AddressOutput; ContractId: ContractIdOutput }>;
export enum InitializationErrorInput {
  CannotReinitialized = 'CannotReinitialized',
}
export enum InitializationErrorOutput {
  CannotReinitialized = 'CannotReinitialized',
}
export type StateInput = Enum<{ Uninitialized: undefined; Initialized: IdentityInput; Revoked: undefined }>;
export type StateOutput = Enum<{ Uninitialized: void; Initialized: IdentityOutput; Revoked: void }>;

export type AddressInput = { bits: string };
export type AddressOutput = AddressInput;
export type AssetIdInput = { bits: string };
export type AssetIdOutput = AssetIdInput;
export type AssetInfoInput = { name: StdString; symbol: StdString; decimals: BigNumberish; mint_amount: BigNumberish };
export type AssetInfoOutput = { name: StdString; symbol: StdString; decimals: number; mint_amount: BN };
export type ContractIdInput = { bits: string };
export type ContractIdOutput = ContractIdInput;
export type CooldownInfoInput = { current_block: BigNumberish; enable_on_block: BigNumberish };
export type CooldownInfoOutput = { current_block: BN; enable_on_block: BN };
export type OwnershipSetInput = { new_owner: IdentityInput };
export type OwnershipSetOutput = { new_owner: IdentityOutput };
export type OwnershipTransferredInput = { new_owner: IdentityInput; previous_owner: IdentityInput };
export type OwnershipTransferredOutput = { new_owner: IdentityOutput; previous_owner: IdentityOutput };
export type SetDecimalsEventInput = { asset: AssetIdInput; decimals: BigNumberish; sender: IdentityInput };
export type SetDecimalsEventOutput = { asset: AssetIdOutput; decimals: number; sender: IdentityOutput };
export type SetNameEventInput = { asset: AssetIdInput; name: Option<StdString>; sender: IdentityInput };
export type SetNameEventOutput = { asset: AssetIdOutput; name: Option<StdString>; sender: IdentityOutput };
export type SetSymbolEventInput = { asset: AssetIdInput; symbol: Option<StdString>; sender: IdentityInput };
export type SetSymbolEventOutput = { asset: AssetIdOutput; symbol: Option<StdString>; sender: IdentityOutput };
export type TotalSupplyEventInput = { asset: AssetIdInput; supply: BigNumberish; sender: IdentityInput };
export type TotalSupplyEventOutput = { asset: AssetIdOutput; supply: BN; sender: IdentityOutput };

const abi = {
  programType: 'contract',
  specVersion: '1.1',
  encodingVersion: '1',
  concreteTypes: [
    {
      type: '()',
      concreteTypeId: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
    },
    {
      type: 'enum ownership::errors::InitializationError',
      concreteTypeId: 'b1fddf488ccb9e63d11888b2750bbd1280a1ae1c49f2d6637fd4cf1e930d1468',
      metadataTypeId: 1,
    },
    {
      type: 'enum src5::AccessError',
      concreteTypeId: 'f1247475d0d1466599267010f088190f8664dd31663a40c5d5e525d8e64b995d',
      metadataTypeId: 2,
    },
    {
      type: 'enum src5::State',
      concreteTypeId: '287a382c1e0b1f11d12a422e77a248d27761327cd17515cc6e6369d528cf31ca',
      metadataTypeId: 3,
    },
    {
      type: 'enum std::identity::Identity',
      concreteTypeId: 'ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335',
      metadataTypeId: 4,
    },
    {
      type: 'enum std::option::Option<struct std::string::String>',
      concreteTypeId: '7c06d929390a9aeeb8ffccf8173ac0d101a9976d99dda01cce74541a81e75ac0',
      metadataTypeId: 5,
      typeArguments: ['9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c'],
    },
    {
      type: 'enum std::option::Option<u64>',
      concreteTypeId: 'd852149004cc9ec0bbe7dc4e37bffea1d41469b759512b6136f2e865a4c06e7d',
      metadataTypeId: 5,
      typeArguments: ['1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0'],
    },
    {
      type: 'enum std::option::Option<u8>',
      concreteTypeId: '2da102c46c7263beeed95818cd7bee801716ba8303dddafdcd0f6c9efda4a0f1',
      metadataTypeId: 5,
      typeArguments: ['c89951a24c6ca28c13fd1cfdc646b2b656d69e61a92b91023be7eb58eb914b6b'],
    },
    {
      type: 'str',
      concreteTypeId: '8c25cb3686462e9a86d2883c5688a22fe738b0bbc85f458d2d2b5f3f667c6d5a',
    },
    {
      type: 'struct AssetInfo',
      concreteTypeId: 'b6e16613b8a0d2559f7197e695f5d5d66696e2cbeed696cc9c1c488bd99db503',
      metadataTypeId: 8,
    },
    {
      type: 'struct CooldownInfo',
      concreteTypeId: '72c8a9103de683ca539d3ae88cff1e5ce3f5aedd663c20a08b6d428de76273a9',
      metadataTypeId: 9,
    },
    {
      type: 'struct ownership::events::OwnershipSet',
      concreteTypeId: '8c0d2488561c35a28ef795bb8bcc4c43999cdd1e3ecbd10c226e0a68660c54d4',
      metadataTypeId: 10,
    },
    {
      type: 'struct ownership::events::OwnershipTransferred',
      concreteTypeId: 'a2a2643e0252b510328c0323a0ea60724fb4cb3309a2322ab31b27566ff9a79d',
      metadataTypeId: 11,
    },
    {
      type: 'struct src20::SetDecimalsEvent',
      concreteTypeId: 'b6a606756ed20ecf9e047dfc134b0a9ba42ccc642956ce4205e784e82ee1daa1',
      metadataTypeId: 12,
    },
    {
      type: 'struct src20::SetNameEvent',
      concreteTypeId: '2c4e26d9fde4e3c732683d47b93ece2ba27aa77cc27495ea42fe5491ef144f0d',
      metadataTypeId: 13,
    },
    {
      type: 'struct src20::SetSymbolEvent',
      concreteTypeId: '3dc850985943a7e8e5becd967e8b8eaa26a7dec1f75a1a80ace5b3bf622b1e1a',
      metadataTypeId: 14,
    },
    {
      type: 'struct src20::TotalSupplyEvent',
      concreteTypeId: '7a3907033239b7e20b602aaf2a1a55863934467688426a359aae8b410786d2ba',
      metadataTypeId: 15,
    },
    {
      type: 'struct std::asset_id::AssetId',
      concreteTypeId: 'c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974',
      metadataTypeId: 17,
    },
    {
      type: 'struct std::string::String',
      concreteTypeId: '9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c',
      metadataTypeId: 21,
    },
    {
      type: 'struct std::vec::Vec<struct AssetInfo>',
      concreteTypeId: '7c14f557c3705f154bf1a29e36dc69da650c07aebd4612cfca7f2a9e4869e513',
      metadataTypeId: 23,
      typeArguments: ['b6e16613b8a0d2559f7197e695f5d5d66696e2cbeed696cc9c1c488bd99db503'],
    },
    {
      type: 'struct std::vec::Vec<struct std::asset_id::AssetId>',
      concreteTypeId: '8b2275934873f381a769c82334e6f66595eeb350d8b2dd012eef4d9bb117942b',
      metadataTypeId: 23,
      typeArguments: ['c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974'],
    },
    {
      type: 'u64',
      concreteTypeId: '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
    },
    {
      type: 'u8',
      concreteTypeId: 'c89951a24c6ca28c13fd1cfdc646b2b656d69e61a92b91023be7eb58eb914b6b',
    },
  ],
  metadataTypes: [
    {
      type: 'b256',
      metadataTypeId: 0,
    },
    {
      type: 'enum ownership::errors::InitializationError',
      metadataTypeId: 1,
      components: [
        {
          name: 'CannotReinitialized',
          typeId: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
        },
      ],
    },
    {
      type: 'enum src5::AccessError',
      metadataTypeId: 2,
      components: [
        {
          name: 'NotOwner',
          typeId: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
        },
      ],
    },
    {
      type: 'enum src5::State',
      metadataTypeId: 3,
      components: [
        {
          name: 'Uninitialized',
          typeId: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
        },
        {
          name: 'Initialized',
          typeId: 4,
        },
        {
          name: 'Revoked',
          typeId: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
        },
      ],
    },
    {
      type: 'enum std::identity::Identity',
      metadataTypeId: 4,
      components: [
        {
          name: 'Address',
          typeId: 16,
        },
        {
          name: 'ContractId',
          typeId: 20,
        },
      ],
    },
    {
      type: 'enum std::option::Option',
      metadataTypeId: 5,
      components: [
        {
          name: 'None',
          typeId: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
        },
        {
          name: 'Some',
          typeId: 6,
        },
      ],
      typeParameters: [6],
    },
    {
      type: 'generic T',
      metadataTypeId: 6,
    },
    {
      type: 'raw untyped ptr',
      metadataTypeId: 7,
    },
    {
      type: 'struct AssetInfo',
      metadataTypeId: 8,
      components: [
        {
          name: 'name',
          typeId: 21,
        },
        {
          name: 'symbol',
          typeId: 21,
        },
        {
          name: 'decimals',
          typeId: 'c89951a24c6ca28c13fd1cfdc646b2b656d69e61a92b91023be7eb58eb914b6b',
        },
        {
          name: 'mint_amount',
          typeId: '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
      ],
    },
    {
      type: 'struct CooldownInfo',
      metadataTypeId: 9,
      components: [
        {
          name: 'current_block',
          typeId: '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
        {
          name: 'enable_on_block',
          typeId: '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
      ],
    },
    {
      type: 'struct ownership::events::OwnershipSet',
      metadataTypeId: 10,
      components: [
        {
          name: 'new_owner',
          typeId: 4,
        },
      ],
    },
    {
      type: 'struct ownership::events::OwnershipTransferred',
      metadataTypeId: 11,
      components: [
        {
          name: 'new_owner',
          typeId: 4,
        },
        {
          name: 'previous_owner',
          typeId: 4,
        },
      ],
    },
    {
      type: 'struct src20::SetDecimalsEvent',
      metadataTypeId: 12,
      components: [
        {
          name: 'asset',
          typeId: 17,
        },
        {
          name: 'decimals',
          typeId: 'c89951a24c6ca28c13fd1cfdc646b2b656d69e61a92b91023be7eb58eb914b6b',
        },
        {
          name: 'sender',
          typeId: 4,
        },
      ],
    },
    {
      type: 'struct src20::SetNameEvent',
      metadataTypeId: 13,
      components: [
        {
          name: 'asset',
          typeId: 17,
        },
        {
          name: 'name',
          typeId: 5,
          typeArguments: [
            {
              name: '',
              typeId: 21,
            },
          ],
        },
        {
          name: 'sender',
          typeId: 4,
        },
      ],
    },
    {
      type: 'struct src20::SetSymbolEvent',
      metadataTypeId: 14,
      components: [
        {
          name: 'asset',
          typeId: 17,
        },
        {
          name: 'symbol',
          typeId: 5,
          typeArguments: [
            {
              name: '',
              typeId: 21,
            },
          ],
        },
        {
          name: 'sender',
          typeId: 4,
        },
      ],
    },
    {
      type: 'struct src20::TotalSupplyEvent',
      metadataTypeId: 15,
      components: [
        {
          name: 'asset',
          typeId: 17,
        },
        {
          name: 'supply',
          typeId: '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
        {
          name: 'sender',
          typeId: 4,
        },
      ],
    },
    {
      type: 'struct std::address::Address',
      metadataTypeId: 16,
      components: [
        {
          name: 'bits',
          typeId: 0,
        },
      ],
    },
    {
      type: 'struct std::asset_id::AssetId',
      metadataTypeId: 17,
      components: [
        {
          name: 'bits',
          typeId: 0,
        },
      ],
    },
    {
      type: 'struct std::bytes::Bytes',
      metadataTypeId: 18,
      components: [
        {
          name: 'buf',
          typeId: 19,
        },
        {
          name: 'len',
          typeId: '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
      ],
    },
    {
      type: 'struct std::bytes::RawBytes',
      metadataTypeId: 19,
      components: [
        {
          name: 'ptr',
          typeId: 7,
        },
        {
          name: 'cap',
          typeId: '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
      ],
    },
    {
      type: 'struct std::contract_id::ContractId',
      metadataTypeId: 20,
      components: [
        {
          name: 'bits',
          typeId: 0,
        },
      ],
    },
    {
      type: 'struct std::string::String',
      metadataTypeId: 21,
      components: [
        {
          name: 'bytes',
          typeId: 18,
        },
      ],
    },
    {
      type: 'struct std::vec::RawVec',
      metadataTypeId: 22,
      components: [
        {
          name: 'ptr',
          typeId: 7,
        },
        {
          name: 'cap',
          typeId: '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
      ],
      typeParameters: [6],
    },
    {
      type: 'struct std::vec::Vec',
      metadataTypeId: 23,
      components: [
        {
          name: 'buf',
          typeId: 22,
          typeArguments: [
            {
              name: '',
              typeId: 6,
            },
          ],
        },
        {
          name: 'len',
          typeId: '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
      ],
      typeParameters: [6],
    },
  ],
  functions: [
    {
      name: 'decimals',
      inputs: [
        {
          name: 'asset',
          concreteTypeId: 'c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974',
        },
      ],
      output: '2da102c46c7263beeed95818cd7bee801716ba8303dddafdcd0f6c9efda4a0f1',
      attributes: [
        {
          name: 'doc-comment',
          arguments: [' Returns the number of decimals an asset uses.'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Arguments'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' * `asset`: [AssetId] - The asset of which to query the decimals.'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Returns'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' * [Option<u8>] - The decimal precision used by `asset`.'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Number of Storage Accesses'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' * Reads: `1`'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Examples'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' ```sway'],
        },
        {
          name: 'doc-comment',
          arguments: [' use src20::SRC20;'],
        },
        {
          name: 'doc-comment',
          arguments: [' use std::constants::DEFAULT_SUB_ID;'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' fn foo(contract_id: ContractId) {'],
        },
        {
          name: 'doc-comment',
          arguments: ['     let src_20_abi = abi(SRC20, contract_id);'],
        },
        {
          name: 'doc-comment',
          arguments: ['     let decimals = src_20_abi.decimals(DEFAULT_SUB_ID);'],
        },
        {
          name: 'doc-comment',
          arguments: ['     assert(decimals.unwrap() == 9u8);'],
        },
        {
          name: 'doc-comment',
          arguments: [' }'],
        },
        {
          name: 'doc-comment',
          arguments: [' ```'],
        },
        {
          name: 'storage',
          arguments: ['read'],
        },
      ],
    },
    {
      name: 'name',
      inputs: [
        {
          name: 'asset',
          concreteTypeId: 'c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974',
        },
      ],
      output: '7c06d929390a9aeeb8ffccf8173ac0d101a9976d99dda01cce74541a81e75ac0',
      attributes: [
        {
          name: 'doc-comment',
          arguments: [' Returns the name of an asset.'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Arguments'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' * `asset`: [AssetId] - The asset of which to query the name.'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Returns'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' * [Option<String>] - The name of `asset`.'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Number of Storage Accesses'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' * Reads: `1`'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Examples'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' ```sway'],
        },
        {
          name: 'doc-comment',
          arguments: [' use src20::SRC20;'],
        },
        {
          name: 'doc-comment',
          arguments: [' use std::constants::DEFAULT_SUB_ID;'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' fn foo(contract_id: ContractId) {'],
        },
        {
          name: 'doc-comment',
          arguments: ['     let src_20_abi = abi(SRC20, contract_id);'],
        },
        {
          name: 'doc-comment',
          arguments: ['     let name = src_20_abi.name(DEFAULT_SUB_ID);'],
        },
        {
          name: 'doc-comment',
          arguments: ['     assert(name.is_some());'],
        },
        {
          name: 'doc-comment',
          arguments: [' }'],
        },
        {
          name: 'doc-comment',
          arguments: [' ```'],
        },
        {
          name: 'storage',
          arguments: ['read'],
        },
      ],
    },
    {
      name: 'symbol',
      inputs: [
        {
          name: 'asset',
          concreteTypeId: 'c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974',
        },
      ],
      output: '7c06d929390a9aeeb8ffccf8173ac0d101a9976d99dda01cce74541a81e75ac0',
      attributes: [
        {
          name: 'doc-comment',
          arguments: [' Returns the symbol of am asset.'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Arguments'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' * `asset`: [AssetId] - The asset of which to query the symbol.'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Returns'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' * [Option<String>] - The symbol of `asset`.'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Number of Storage Accesses'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' * Reads: `1`'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Examples'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' ```sway'],
        },
        {
          name: 'doc-comment',
          arguments: [' use src20::SRC20;'],
        },
        {
          name: 'doc-comment',
          arguments: [' use std::constants::DEFAULT_SUB_ID;'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' fn foo(contract_id: ContractId) {'],
        },
        {
          name: 'doc-comment',
          arguments: ['     let src_20_abi = abi(SRC20, contract_id);'],
        },
        {
          name: 'doc-comment',
          arguments: ['     let symbol = src_20_abi.symbol(DEFAULT_SUB_ID);'],
        },
        {
          name: 'doc-comment',
          arguments: ['     assert(symbol.is_some());'],
        },
        {
          name: 'doc-comment',
          arguments: [' }'],
        },
        {
          name: 'doc-comment',
          arguments: [' ```'],
        },
        {
          name: 'storage',
          arguments: ['read'],
        },
      ],
    },
    {
      name: 'total_assets',
      inputs: [],
      output: '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
      attributes: [
        {
          name: 'doc-comment',
          arguments: [' Returns the total number of individual assets minted  by this contract.'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Additional Information'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' For this single asset contract, this is always one.'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Returns'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' * [u64] - The number of assets that this contract has minted.'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Number of Storage Accesses'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' * Reads: `1`'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Examples'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' ```sway'],
        },
        {
          name: 'doc-comment',
          arguments: [' use src20::SRC20;'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' fn foo(contract_id: ContractId) {'],
        },
        {
          name: 'doc-comment',
          arguments: ['     let src_20_abi = abi(SRC20, contract_id);'],
        },
        {
          name: 'doc-comment',
          arguments: ['     let assets = src_20_abi.total_assets();'],
        },
        {
          name: 'doc-comment',
          arguments: ['     assert(assets == 1);'],
        },
        {
          name: 'doc-comment',
          arguments: [' }'],
        },
        {
          name: 'doc-comment',
          arguments: [' ```'],
        },
        {
          name: 'storage',
          arguments: ['read'],
        },
      ],
    },
    {
      name: 'total_supply',
      inputs: [
        {
          name: 'asset',
          concreteTypeId: 'c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974',
        },
      ],
      output: 'd852149004cc9ec0bbe7dc4e37bffea1d41469b759512b6136f2e865a4c06e7d',
      attributes: [
        {
          name: 'doc-comment',
          arguments: [' Returns the total supply of coins for an asset.'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Arguments'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' * `asset`: [AssetId] - The asset of which to query the total supply.'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Returns'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' * [Option<u64>] - The total supply of an `asset`.'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Number of Storage Accesses'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' * Reads: `1`'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Examples'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' ```sway'],
        },
        {
          name: 'doc-comment',
          arguments: [' use src20::SRC20;'],
        },
        {
          name: 'doc-comment',
          arguments: [' use std::constants::DEFAULT_SUB_ID;'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' fn foo(contract_id: ContractId) {'],
        },
        {
          name: 'doc-comment',
          arguments: ['     let src_20_abi = abi(SRC20, contract_id);'],
        },
        {
          name: 'doc-comment',
          arguments: ['     let supply = src_20_abi.total_supply(DEFAULT_SUB_ID);'],
        },
        {
          name: 'doc-comment',
          arguments: ['     assert(supply.unwrap() != 0);'],
        },
        {
          name: 'doc-comment',
          arguments: [' }'],
        },
        {
          name: 'doc-comment',
          arguments: [' ```'],
        },
        {
          name: 'storage',
          arguments: ['read'],
        },
      ],
    },
    {
      name: 'owner',
      inputs: [],
      output: '287a382c1e0b1f11d12a422e77a248d27761327cd17515cc6e6369d528cf31ca',
      attributes: [
        {
          name: 'storage',
          arguments: ['read'],
        },
      ],
    },
    {
      name: 'admin_mint_asset',
      inputs: [
        {
          name: 'recipient',
          concreteTypeId: 'ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335',
        },
        {
          name: 'symbol',
          concreteTypeId: '9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c',
        },
        {
          name: 'mint_amount',
          concreteTypeId: '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
      ],
      output: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
      attributes: [
        {
          name: 'storage',
          arguments: ['read', 'write'],
        },
      ],
    },
    {
      name: 'initialize',
      inputs: [
        {
          name: 'owner',
          concreteTypeId: 'ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335',
        },
      ],
      output: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
      attributes: [
        {
          name: 'storage',
          arguments: ['read', 'write'],
        },
      ],
    },
    {
      name: 'initialize_assets',
      inputs: [
        {
          name: 'assets',
          concreteTypeId: '7c14f557c3705f154bf1a29e36dc69da650c07aebd4612cfca7f2a9e4869e513',
        },
      ],
      output: '8b2275934873f381a769c82334e6f66595eeb350d8b2dd012eef4d9bb117942b',
      attributes: [
        {
          name: 'storage',
          arguments: ['read', 'write'],
        },
      ],
    },
    {
      name: 'mint_asset',
      inputs: [
        {
          name: 'recipient',
          concreteTypeId: 'ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335',
        },
        {
          name: 'symbol',
          concreteTypeId: '9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c',
        },
      ],
      output: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
      attributes: [
        {
          name: 'storage',
          arguments: ['read', 'write'],
        },
      ],
    },
    {
      name: 'mint_cooldown',
      inputs: [
        {
          name: 'recipient',
          concreteTypeId: 'ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335',
        },
        {
          name: 'symbol',
          concreteTypeId: '9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c',
        },
      ],
      output: '72c8a9103de683ca539d3ae88cff1e5ce3f5aedd663c20a08b6d428de76273a9',
      attributes: [
        {
          name: 'storage',
          arguments: ['read'],
        },
      ],
    },
    {
      name: 'set_cooldown_period',
      inputs: [
        {
          name: 'cooldown_period',
          concreteTypeId: '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
      ],
      output: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
      attributes: [
        {
          name: 'storage',
          arguments: ['read', 'write'],
        },
      ],
    },
    {
      name: 'set_mint_amount',
      inputs: [
        {
          name: 'symbol',
          concreteTypeId: '9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c',
        },
        {
          name: 'mint_amount',
          concreteTypeId: '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
      ],
      output: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
      attributes: [
        {
          name: 'storage',
          arguments: ['read', 'write'],
        },
      ],
    },
    {
      name: 'transfer_ownership',
      inputs: [
        {
          name: 'new_owner',
          concreteTypeId: 'ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335',
        },
      ],
      output: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
      attributes: [
        {
          name: 'storage',
          arguments: ['read', 'write'],
        },
      ],
    },
  ],
  loggedTypes: [
    {
      logId: '17376141311665587813',
      concreteTypeId: 'f1247475d0d1466599267010f088190f8664dd31663a40c5d5e525d8e64b995d',
    },
    {
      logId: '10098701174489624218',
      concreteTypeId: '8c25cb3686462e9a86d2883c5688a22fe738b0bbc85f458d2d2b5f3f667c6d5a',
    },
    {
      logId: '12825652816513834595',
      concreteTypeId: 'b1fddf488ccb9e63d11888b2750bbd1280a1ae1c49f2d6637fd4cf1e930d1468',
    },
    {
      logId: '10091762507985991074',
      concreteTypeId: '8c0d2488561c35a28ef795bb8bcc4c43999cdd1e3ecbd10c226e0a68660c54d4',
    },
    {
      logId: '3192531903561655239',
      concreteTypeId: '2c4e26d9fde4e3c732683d47b93ece2ba27aa77cc27495ea42fe5491ef144f0d',
    },
    {
      logId: '4451896846918592488',
      concreteTypeId: '3dc850985943a7e8e5becd967e8b8eaa26a7dec1f75a1a80ace5b3bf622b1e1a',
    },
    {
      logId: '13161214062477053647',
      concreteTypeId: 'b6a606756ed20ecf9e047dfc134b0a9ba42ccc642956ce4205e784e82ee1daa1',
    },
    {
      logId: '8807078256608655330',
      concreteTypeId: '7a3907033239b7e20b602aaf2a1a55863934467688426a359aae8b410786d2ba',
    },
    {
      logId: '11719039397861176592',
      concreteTypeId: 'a2a2643e0252b510328c0323a0ea60724fb4cb3309a2322ab31b27566ff9a79d',
    },
  ],
  messagesTypes: [],
  configurables: [],
  errorCodes: {},
};

const storageSlots: StorageSlot[] = [
  {
    key: 'ad0db2b0fc00bf54d2d0159d8639f4a8f48be8403564992aaaac00d69daa3137',
    value: '0000000000000000000000000000000000000000000000000000000000000000',
  },
  {
    key: 'eeee7cc0a0ee6d2945f7cfef51b7c220079d5a0861154baa6181563213677857',
    value: '000000000000003c000000000000000000000000000000000000000000000000',
  },
];

export class Src20TokenInterface extends Interface {
  constructor() {
    super(abi);
  }

  declare functions: {
    decimals: FunctionFragment;
    name: FunctionFragment;
    symbol: FunctionFragment;
    total_assets: FunctionFragment;
    total_supply: FunctionFragment;
    owner: FunctionFragment;
    admin_mint_asset: FunctionFragment;
    initialize: FunctionFragment;
    initialize_assets: FunctionFragment;
    mint_asset: FunctionFragment;
    mint_cooldown: FunctionFragment;
    set_cooldown_period: FunctionFragment;
    set_mint_amount: FunctionFragment;
    transfer_ownership: FunctionFragment;
  };
}

export class Src20Token extends __Contract {
  static readonly abi = abi;
  static readonly storageSlots = storageSlots;

  declare interface: Src20TokenInterface;
  declare functions: {
    decimals: InvokeFunction<[asset: AssetIdInput], Option<number>>;
    name: InvokeFunction<[asset: AssetIdInput], Option<StdString>>;
    symbol: InvokeFunction<[asset: AssetIdInput], Option<StdString>>;
    total_assets: InvokeFunction<[], BN>;
    total_supply: InvokeFunction<[asset: AssetIdInput], Option<BN>>;
    owner: InvokeFunction<[], StateOutput>;
    admin_mint_asset: InvokeFunction<[recipient: IdentityInput, symbol: StdString, mint_amount: BigNumberish], void>;
    initialize: InvokeFunction<[owner: IdentityInput], void>;
    initialize_assets: InvokeFunction<[assets: Vec<AssetInfoInput>], Vec<AssetIdOutput>>;
    mint_asset: InvokeFunction<[recipient: IdentityInput, symbol: StdString], void>;
    mint_cooldown: InvokeFunction<[recipient: IdentityInput, symbol: StdString], CooldownInfoOutput>;
    set_cooldown_period: InvokeFunction<[cooldown_period: BigNumberish], void>;
    set_mint_amount: InvokeFunction<[symbol: StdString, mint_amount: BigNumberish], void>;
    transfer_ownership: InvokeFunction<[new_owner: IdentityInput], void>;
  };

  constructor(id: string | Address, accountOrProvider: Account | Provider) {
    super(id, abi, accountOrProvider);
  }
}
