/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.102.0
  Forc version: 0.69.1
  Fuel-Core version: 0.47.1
*/

import { Contract as __Contract, Interface } from 'fuels';
import type {
  Provider,
  Account,
  StorageSlot,
  Address,
  BigNumberish,
  BN,
  FunctionFragment,
  InvokeFunction,
  StrSlice,
} from 'fuels';

import type { Option, Enum } from './common';

export enum AccessErrorInput {
  NotOwner = 'NotOwner',
}
export enum AccessErrorOutput {
  NotOwner = 'NotOwner',
}
export type IdentityInput = Enum<{ Address: AddressInput; ContractId: ContractIdInput }>;
export type IdentityOutput = Enum<{ Address: AddressOutput; ContractId: ContractIdOutput }>;
export enum InitializationErrorInput {
  CannotReinitialized = 'CannotReinitialized',
}
export enum InitializationErrorOutput {
  CannotReinitialized = 'CannotReinitialized',
}
export type SignatureInput = Enum<{ Secp256k1: Secp256k1Input; Secp256r1: Secp256r1Input; Ed25519: Ed25519Input }>;
export type SignatureOutput = Enum<{ Secp256k1: Secp256k1Output; Secp256r1: Secp256r1Output; Ed25519: Ed25519Output }>;
export type StateInput = Enum<{ Uninitialized: undefined; Initialized: IdentityInput; Revoked: undefined }>;
export type StateOutput = Enum<{ Uninitialized: void; Initialized: IdentityOutput; Revoked: void }>;

export type AddressInput = { bits: string };
export type AddressOutput = AddressInput;
export type ContractIdInput = { bits: string };
export type ContractIdOutput = ContractIdInput;
export type Ed25519Input = {
  bits: [
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
  ];
};
export type Ed25519Output = {
  bits: [
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
  ];
};
export type IncrementNonceEventInput = { nonce: BigNumberish };
export type IncrementNonceEventOutput = { nonce: BN };
export type OwnershipTransferredEventInput = {
  previous_owner: Option<IdentityInput>;
  new_owner: IdentityInput;
  timestamp: TimeInput;
};
export type OwnershipTransferredEventOutput = {
  previous_owner: Option<IdentityOutput>;
  new_owner: IdentityOutput;
  timestamp: TimeOutput;
};
export type ProxyTargetSetInput = { new_target: ContractIdInput };
export type ProxyTargetSetOutput = { new_target: ContractIdOutput };
export type Secp256k1Input = {
  bits: [
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
  ];
};
export type Secp256k1Output = {
  bits: [
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
  ];
};
export type Secp256r1Input = {
  bits: [
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
    BigNumberish,
  ];
};
export type Secp256r1Output = {
  bits: [
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
  ];
};
export type TimeInput = { unix: BigNumberish };
export type TimeOutput = { unix: BN };

export type TradeAccountProxyConfigurables = Partial<{
  ORACLE_CONTRACT_ID: ContractIdInput;
  INITIAL_OWNER: StateInput;
}>;

const abi = {
  programType: 'contract',
  specVersion: '1.1',
  encodingVersion: '1',
  concreteTypes: [
    {
      type: '()',
      concreteTypeId: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
    },
    {
      type: 'enum ownership::errors::InitializationError',
      concreteTypeId: 'b1fddf488ccb9e63d11888b2750bbd1280a1ae1c49f2d6637fd4cf1e930d1468',
      metadataTypeId: 2,
    },
    {
      type: 'enum src5::AccessError',
      concreteTypeId: 'f1247475d0d1466599267010f088190f8664dd31663a40c5d5e525d8e64b995d',
      metadataTypeId: 3,
    },
    {
      type: 'enum src5::State',
      concreteTypeId: '287a382c1e0b1f11d12a422e77a248d27761327cd17515cc6e6369d528cf31ca',
      metadataTypeId: 4,
    },
    {
      type: 'enum std::crypto::signature::Signature',
      concreteTypeId: '2a32867dec49ed8ddf6b7d2ed19d53c626d3f593369b5dd82a317d7b300e1c39',
      metadataTypeId: 5,
    },
    {
      type: 'enum std::option::Option<enum std::crypto::signature::Signature>',
      concreteTypeId: '8c8a9aeea8dc1a1ac1f1fe31c77823653152feda3fa93cd494eedbf84395ca40',
      metadataTypeId: 7,
      typeArguments: ['2a32867dec49ed8ddf6b7d2ed19d53c626d3f593369b5dd82a317d7b300e1c39'],
    },
    {
      type: 'enum std::option::Option<struct std::contract_id::ContractId>',
      concreteTypeId: '0d79387ad3bacdc3b7aad9da3a96f4ce60d9a1b6002df254069ad95a3931d5c8',
      metadataTypeId: 7,
      typeArguments: ['29c10735d33b5159f0c71ee1dbd17b36a3e69e41f00fab0d42e1bd9f428d8a54'],
    },
    {
      type: 'str',
      concreteTypeId: '8c25cb3686462e9a86d2883c5688a22fe738b0bbc85f458d2d2b5f3f667c6d5a',
    },
    {
      type: 'struct contract_libs::signature::IncrementNonceEvent',
      concreteTypeId: '1f60fe48a54d08956985da0422f2d7d44834b7c4d4687f0376f26dce46fe44bf',
      metadataTypeId: 9,
    },
    {
      type: 'struct contract_schema::proxys::OwnershipTransferredEvent',
      concreteTypeId: '1a4a391e4e527b56f6e488bce418bfd7ff45c5ee2956b4891af265057da0ae69',
      metadataTypeId: 10,
    },
    {
      type: 'struct std::contract_id::ContractId',
      concreteTypeId: '29c10735d33b5159f0c71ee1dbd17b36a3e69e41f00fab0d42e1bd9f428d8a54',
      metadataTypeId: 12,
    },
    {
      type: 'struct upgradability::events::ProxyTargetSet',
      concreteTypeId: '47d9868a6266fb294f68de9d33690c9e627c37425d784cc82b7a7b7e5635b779',
      metadataTypeId: 17,
    },
  ],
  metadataTypes: [
    {
      type: '[_; 64]',
      metadataTypeId: 0,
      components: [
        {
          name: '__array_element',
          typeId: 19,
        },
      ],
    },
    {
      type: 'b256',
      metadataTypeId: 1,
    },
    {
      type: 'enum ownership::errors::InitializationError',
      metadataTypeId: 2,
      components: [
        {
          name: 'CannotReinitialized',
          typeId: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
        },
      ],
    },
    {
      type: 'enum src5::AccessError',
      metadataTypeId: 3,
      components: [
        {
          name: 'NotOwner',
          typeId: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
        },
      ],
    },
    {
      type: 'enum src5::State',
      metadataTypeId: 4,
      components: [
        {
          name: 'Uninitialized',
          typeId: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
        },
        {
          name: 'Initialized',
          typeId: 6,
        },
        {
          name: 'Revoked',
          typeId: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
        },
      ],
    },
    {
      type: 'enum std::crypto::signature::Signature',
      metadataTypeId: 5,
      components: [
        {
          name: 'Secp256k1',
          typeId: 14,
        },
        {
          name: 'Secp256r1',
          typeId: 15,
        },
        {
          name: 'Ed25519',
          typeId: 13,
        },
      ],
    },
    {
      type: 'enum std::identity::Identity',
      metadataTypeId: 6,
      components: [
        {
          name: 'Address',
          typeId: 11,
        },
        {
          name: 'ContractId',
          typeId: 12,
        },
      ],
    },
    {
      type: 'enum std::option::Option',
      metadataTypeId: 7,
      components: [
        {
          name: 'None',
          typeId: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
        },
        {
          name: 'Some',
          typeId: 8,
        },
      ],
      typeParameters: [8],
    },
    {
      type: 'generic T',
      metadataTypeId: 8,
    },
    {
      type: 'struct contract_libs::signature::IncrementNonceEvent',
      metadataTypeId: 9,
      components: [
        {
          name: 'nonce',
          typeId: 18,
        },
      ],
    },
    {
      type: 'struct contract_schema::proxys::OwnershipTransferredEvent',
      metadataTypeId: 10,
      components: [
        {
          name: 'previous_owner',
          typeId: 7,
          typeArguments: [
            {
              name: '',
              typeId: 6,
            },
          ],
        },
        {
          name: 'new_owner',
          typeId: 6,
        },
        {
          name: 'timestamp',
          typeId: 16,
        },
      ],
    },
    {
      type: 'struct std::address::Address',
      metadataTypeId: 11,
      components: [
        {
          name: 'bits',
          typeId: 1,
        },
      ],
    },
    {
      type: 'struct std::contract_id::ContractId',
      metadataTypeId: 12,
      components: [
        {
          name: 'bits',
          typeId: 1,
        },
      ],
    },
    {
      type: 'struct std::crypto::ed25519::Ed25519',
      metadataTypeId: 13,
      components: [
        {
          name: 'bits',
          typeId: 0,
        },
      ],
    },
    {
      type: 'struct std::crypto::secp256k1::Secp256k1',
      metadataTypeId: 14,
      components: [
        {
          name: 'bits',
          typeId: 0,
        },
      ],
    },
    {
      type: 'struct std::crypto::secp256r1::Secp256r1',
      metadataTypeId: 15,
      components: [
        {
          name: 'bits',
          typeId: 0,
        },
      ],
    },
    {
      type: 'struct std::time::Time',
      metadataTypeId: 16,
      components: [
        {
          name: 'unix',
          typeId: 18,
        },
      ],
    },
    {
      type: 'struct upgradability::events::ProxyTargetSet',
      metadataTypeId: 17,
      components: [
        {
          name: 'new_target',
          typeId: 12,
        },
      ],
    },
    {
      type: 'u64',
      metadataTypeId: 18,
    },
    {
      type: 'u8',
      metadataTypeId: 19,
    },
  ],
  functions: [
    {
      name: 'proxy_owner',
      inputs: [],
      output: '287a382c1e0b1f11d12a422e77a248d27761327cd17515cc6e6369d528cf31ca',
      attributes: [
        {
          name: 'doc-comment',
          arguments: [' Returns the owner of the proxy contract.'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Returns'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' * [State] - Represents the state of ownership for this contract.'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Number of Storage Accesses'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' * Reads: `1`'],
        },
        {
          name: 'storage',
          arguments: ['read'],
        },
      ],
    },
    {
      name: 'proxy_target',
      inputs: [],
      output: '0d79387ad3bacdc3b7aad9da3a96f4ce60d9a1b6002df254069ad95a3931d5c8',
      attributes: [
        {
          name: 'doc-comment',
          arguments: [' Returns the target contract of the proxy contract.'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Returns'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [
            ' * [Option<ContractId>] - The new proxy contract to which all fallback calls will be passed or `None`.',
          ],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Number of Storage Accesses'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' * Reads: `1`'],
        },
        {
          name: 'storage',
          arguments: ['read'],
        },
      ],
    },
    {
      name: 'set_proxy_target',
      inputs: [
        {
          name: '_new_target',
          concreteTypeId: '29c10735d33b5159f0c71ee1dbd17b36a3e69e41f00fab0d42e1bd9f428d8a54',
        },
      ],
      output: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
      attributes: [
        {
          name: 'doc-comment',
          arguments: [' Change the target contract of the proxy contract.'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Additional Information'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' This method can only be called by the `proxy_owner`.'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Arguments'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [
            ' * `new_target`: [ContractId] - The new proxy contract to which all fallback calls will be passed.',
          ],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Reverts'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' * When not called by `proxy_owner`.'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Number of Storage Accesses'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' * Reads: `1`'],
        },
        {
          name: 'doc-comment',
          arguments: [' * Write: `1`'],
        },
        {
          name: 'storage',
          arguments: ['read', 'write'],
        },
      ],
    },
    {
      name: 'check_upgrade',
      inputs: [],
      output: '0d79387ad3bacdc3b7aad9da3a96f4ce60d9a1b6002df254069ad95a3931d5c8',
      attributes: [
        {
          name: 'doc-comment',
          arguments: [' Checks if an upgrade is available for this trading account.'],
        },
        {
          name: 'doc-comment',
          arguments: [' Queries the oracle contract for any pending upgrades.'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Returns'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [
            ' * `Option<ContractId>` - The new implementation contract ID if upgrade is available, None otherwise',
          ],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Storage Access'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' - Reads: Oracle contract ID from configurables'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # External Calls'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' - Calls the oracle contract to check for upgrades'],
        },
        {
          name: 'storage',
          arguments: ['read'],
        },
      ],
    },
    {
      name: 'initialize',
      inputs: [],
      output: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
      attributes: [
        {
          name: 'doc-comment',
          arguments: [' Initializes the proxy contract.'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Additional Information'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [
            ' This method sets the storage values using the values of the configurable constants `INITIAL_TARGET` and `INITIAL_OWNER`.',
          ],
        },
        {
          name: 'doc-comment',
          arguments: [' This then allows methods that write to storage to be called.'],
        },
        {
          name: 'doc-comment',
          arguments: [' This method can only be called once.'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Reverts'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' * When `storage::SRC14.proxy_owner` is not [State::Uninitialized].'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Number of Storage Accesses'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' * Writes: `2`'],
        },
        {
          name: 'storage',
          arguments: ['write'],
        },
      ],
    },
    {
      name: 'set_proxy_target_with_signature',
      inputs: [
        {
          name: 'signature',
          concreteTypeId: '8c8a9aeea8dc1a1ac1f1fe31c77823653152feda3fa93cd494eedbf84395ca40',
        },
      ],
      output: '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
      attributes: [
        {
          name: 'doc-comment',
          arguments: [' Change the target contract of the proxy contract.'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Additional Information'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' This method can only be called by the `proxy_owner`.'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Arguments'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [
            ' * `new_target`: [ContractId] - The new proxy contract to which all fallback calls will be passed.',
          ],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Reverts'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' * When not called by `proxy_owner`.'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' # Number of Storage Accesses'],
        },
        {
          name: 'doc-comment',
          arguments: [''],
        },
        {
          name: 'doc-comment',
          arguments: [' * Reads: `1`'],
        },
        {
          name: 'doc-comment',
          arguments: [' * Write: `1`'],
        },
        {
          name: 'storage',
          arguments: ['read', 'write'],
        },
      ],
    },
  ],
  loggedTypes: [
    {
      logId: '17376141311665587813',
      concreteTypeId: 'f1247475d0d1466599267010f088190f8664dd31663a40c5d5e525d8e64b995d',
    },
    {
      logId: '10098701174489624218',
      concreteTypeId: '8c25cb3686462e9a86d2883c5688a22fe738b0bbc85f458d2d2b5f3f667c6d5a',
    },
    {
      logId: '5177317175553620777',
      concreteTypeId: '47d9868a6266fb294f68de9d33690c9e627c37425d784cc82b7a7b7e5635b779',
    },
    {
      logId: '12825652816513834595',
      concreteTypeId: 'b1fddf488ccb9e63d11888b2750bbd1280a1ae1c49f2d6637fd4cf1e930d1468',
    },
    {
      logId: '1894389395588545366',
      concreteTypeId: '1a4a391e4e527b56f6e488bce418bfd7ff45c5ee2956b4891af265057da0ae69',
    },
    {
      logId: '2261086600904378517',
      concreteTypeId: '1f60fe48a54d08956985da0422f2d7d44834b7c4d4687f0376f26dce46fe44bf',
    },
  ],
  messagesTypes: [],
  configurables: [
    {
      name: 'ORACLE_CONTRACT_ID',
      concreteTypeId: '29c10735d33b5159f0c71ee1dbd17b36a3e69e41f00fab0d42e1bd9f428d8a54',
      offset: 29496,
      indirect: false,
    },
    {
      name: 'INITIAL_OWNER',
      concreteTypeId: '287a382c1e0b1f11d12a422e77a248d27761327cd17515cc6e6369d528cf31ca',
      offset: 29448,
      indirect: false,
    },
  ],
  errorCodes: {},
};

const storageSlots: StorageSlot[] = [
  {
    key: '7bb458adc1d118713319a5baa00a2d049dd64d2916477d2688d76970c898cd55',
    value: '0000000000000000000000000000000000000000000000000000000000000000',
  },
  {
    key: '7bb458adc1d118713319a5baa00a2d049dd64d2916477d2688d76970c898cd56',
    value: '0000000000000000000000000000000000000000000000000000000000000000',
  },
  {
    key: 'bb79927b15d9259ea316f2ecb2297d6cc8851888a98278c0a2e03e1a091ea754',
    value: '0000000000000000000000000000000000000000000000000000000000000000',
  },
  {
    key: 'bb79927b15d9259ea316f2ecb2297d6cc8851888a98278c0a2e03e1a091ea755',
    value: '0000000000000000000000000000000000000000000000000000000000000000',
  },
];

export class TradeAccountProxyInterface extends Interface {
  constructor() {
    super(abi);
  }

  declare functions: {
    proxy_owner: FunctionFragment;
    proxy_target: FunctionFragment;
    set_proxy_target: FunctionFragment;
    check_upgrade: FunctionFragment;
    initialize: FunctionFragment;
    set_proxy_target_with_signature: FunctionFragment;
  };
}

export class TradeAccountProxy extends __Contract {
  static readonly abi = abi;
  static readonly storageSlots = storageSlots;

  declare interface: TradeAccountProxyInterface;
  declare functions: {
    proxy_owner: InvokeFunction<[], StateOutput>;
    proxy_target: InvokeFunction<[], Option<ContractIdOutput>>;
    set_proxy_target: InvokeFunction<[_new_target: ContractIdInput], void>;
    check_upgrade: InvokeFunction<[], Option<ContractIdOutput>>;
    initialize: InvokeFunction<[], void>;
    set_proxy_target_with_signature: InvokeFunction<[signature?: Option<SignatureInput>], void>;
  };

  constructor(id: string | Address, accountOrProvider: Account | Provider) {
    super(id, abi, accountOrProvider);
  }
}
